# Generated by Django 2.2.5 on 2019-09-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TocoModel',
            fields=[
                #primary_key=Trueは主キー、つまりその項目がユニーク番号が振られていることを示す
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField()),
            ],
        ),
    ]
