# Generated by Django 2.2.5 on 2019-09-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TocoModel',
            new_name='TodoModel',
        ),
    ]
